version: "3.9"

services:
  database:
    image: postgres
    container_name: database_jetops
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=jetops
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: jetops
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local
